version: '3'
services:
  web:
    image: python:3.8
    container_name: mi_servicio_python
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    command: sh -c "pip install --upgrade pip && pip install -r /app/requirements.txt && python /app/run.py"
    working_dir: /app
    depends_on:
      - database

  database:
    image: postgres:13
    container_name: sprint_final

    environment:
      POSTGRES_DB: sprint_final
      POSTGRES_USER: sprint_final
      POSTGRES_PASSWORD: sprint_final
    ports:
      - "5432:5432"
    volumes:
      - ./datos_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
