version: '3'
services:
  web:
    image: python:3.8
    container_name: mi_servicio_python
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    command: sh -c "pip install --upgrade pip && pip install -r /app/requirements.txt && python /app/run.py"
    working_dir: /app
    depends_on:
      - database
      - jenkins
      - grafana
      - prometheus

  database:
    image: postgres:13
    container_name: sprint_final
    environment:
      POSTGRES_DB: sprint_final
      POSTGRES_USER: sprint_final
      POSTGRES_PASSWORD: sprint_final
    ports:
      - "5432:5432"
    volumes:
      - ./datos_postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  jenkins:
    image: jenkins/jenkins:lts
    container_name: mi_servicio_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_home:/var/jenkins_home

  grafana:
    image: grafana/grafana:latest
    container_name: mi_servicio_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana_data:/var/lib/grafana

  prometheus:
    image: prom/prometheus:latest
    container_name: mi_servicio_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data:/etc/prometheus
