version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DATABASE_URI: "postgresql://sprint_final:sprint_final@db/sprint_final"
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_DB: sprint_final
      POSTGRES_USER: sprint_final
      POSTGRES_PASSWORD: sprint_final
