global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'python-app'
    static_configs:
      - targets: ['web:5000']
    metrics_path: /metrics
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']
